INSERT INTO JOG (DATE, DISTANCE, LOCATION, TIME, MINUTES) VALUES (CURRENT_DATE(), 10, 'NEW YORK', CURRENT_TIME(), 60);
INSERT INTO JOG (DATE, DISTANCE, LOCATION, TIME, MINUTES) VALUES (CURRENT_DATE(), 1, 'TORONTO', CURRENT_TIME(), 34);
INSERT INTO JOG (DATE, DISTANCE, LOCATION, TIME, MINUTES) VALUES (CURRENT_DATE(), 2, 'NEW YORK', CURRENT_TIME(), 33);
INSERT INTO JOG (DATE, DISTANCE, LOCATION, TIME, MINUTES) VALUES (CURRENT_DATE(), 20, 'OTTAWA', CURRENT_TIME(), 90);
SELECT * FROM JOG;